version: '3.8'

services:
  app:
    container_name: oficina-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://oficina-db:5432/oficina_db
      SPRING_DATASOURCE_USERNAME: oficina_admin
      SPRING_DATASOURCE_PASSWORD: oficina_password
      API_SECURITY_TOKEN_SECRET: dev_secret_key_for_jwt_development
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: oficina-db
    image: postgres:13
    environment:
      POSTGRES_DB: oficina_db
      POSTGRES_USER: oficina_admin
      POSTGRES_PASSWORD: oficina_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
