apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
type: Opaque
data:
  # Valores codificados em Base64 (ex: echo -n "valor" | base64)
  # db-password: oficina_password
  db-password: b2ZpY2luYV9wYXNzd29yZA==
  # jwt-secret: dev_secret_key_for_jwt_development
  jwt-secret: ZGV2X3NlY3JldF9rZXlfZm9yX2p3dF9kZXZlbG9wbWVudA==
