apiVersion: v1
kind: Service
metadata:
  name: oficina-service
spec:
  selector:
    app: oficina-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # Use LoadBalancer se for usar Ingress
