apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
data:
  db-url: ${SPRING_DATASOURCE_URL} # Alterado para placeholder, será preenchido via CI/CD ou Secret
  db-username: oficina_admin
  mail-host: oficina-mailhog
  mail-port: "1025"
  new-relic-app-name: fiap-tech-challenge-app
  new-relic-environment: production
  new-relic-distributed-tracing-enabled: "true"
  new-relic-application-logging-enabled: "true"
  new-relic-application-logging-forwarding-enabled: "true"
