apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
type: Opaque
stringData:
  # Senhas reais para o ambiente de dev/teste (Kubernetes Local)
  db-password: oficina_password
  jwt-secret: dev_secret_key_for_jwt_development
