spring:
  application:
    name: oficina-mecanica-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/oficina_db}
    username: ${SPRING_DATASOURCE_USERNAME:oficina_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:oficina_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Cria as tabelas automaticamente com base nas Entidades Ricas
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.oficina: DEBUG